nb_web:
    resource: "@NBWebBundle/Resources/config/routing.yml"
    prefix:   /

nb_core:
    resource: "@NBCoreBundle/Resources/config/routing.yml"
    prefix:   /core

nb_admin:
    resource: "@NBAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

