<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWtqzkdq\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWtqzkdq/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWtqzkdq.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWtqzkdq\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerWtqzkdq\appDevDebugProjectContainer([
    'container.build_hash' => 'Wtqzkdq',
    'container.build_id' => '38871408',
    'container.build_time' => 1626367957,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWtqzkdq');
